### PR TITLE
chore: upgrade probot and dependencies

### PR DESCRIPTION
**Pull request by krohrsb**
This upgrades probot to v9.

- Probot to v9
- Probot Config v1.1
- Octokit upgrade to match probot v9
- Octokit API usage to conform.
- Update dev deps to current range
- Make node 10 the minimum

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@krohrsb As you already have this PR that is updating the dependencies would you mind also updating `conventional-commit-types` to be `^2.3.0`? Now that [`conventional-commit-types` PR 13](https://github.com/commitizen/conventional-commit-types/pull/13) has been merged this would solve Issue #72, and seems like it would be within the scope of this PR.

**Comment by matthewfeickert** [comment]
Updating `conventional-commit-types` to be `^2.3.0` would also necessarily require [updating the `README`](https://github.com/probot/semantic-pull-requests/blob/66e17d59935ec944b735ba48fb815fd4648e9428/README.md#configuration). @zeke, is that okay to do in the same PR or if it would be preferable to keep dependency changes that affect the docs to be more atomic?

**Comment by zeke** [comment]
I'm okay with either approach. Thanks for asking, and apologies for not noticing this PR earlier. Thanks for the ping!

**Comment by matthewfeickert** [comment]
> I'm okay with either approach. 

Great! In this case, once @krohrsb has rebased their PR I can just make a PR against theirs that adds in the doc changes, unless they beat me to it.

**Comment by zeke** [comment]
Looks like this PR is gathering dust. Do you all still want to see it ship?

**Comment by matthewfeickert** [comment]
> Looks like this PR is gathering dust. Do you all still want to see it ship?

Given Issue #72 my team no longer needs this, so it is up to you and @krohrsb now.

**Comment by zeke** [comment]
I'd be in favor of closing this and installing @dependabot instead. What do you think, @krohrsb?

**Comment by krohrsb** [comment]
Yeah that's fine

**Pull request closed without merging**
