### PR TITLE
feat: update parse-commit-message to support bang suffix for breaking changes

### PR DESCRIPTION
**Pull request by zeke**
Resolves https://github.com/zeke/semantic-pull-requests/issues/73

### CODE REVIEW

**Comment by tunnckoCore** [comment]
I'll check. Should have problems.

**Comment by tunnckoCore** [comment]
@zeke,

this here https://github.com/zeke/semantic-pull-requests/blob/master/lib/is-semantic-message.js#L5 makes me think it is possible `message` to be falsey value which probably is the problem, because `validate` can only accept `PossibleCommit` which is one of 1) non empty string, 2) `Commit` object, or array of previous ones. And doesn't accept second argument anymore.

**Comment by tunnckoCore** [comment]
Okay, it seems there are few more thigns that need to be updated, but quick fix for now can be to make a check if there is results in the `value` / `commits`.

Like

```js
if (!result) return false
```

**Comment by tunnckoCore** [comment]
Published one more version (`next` dist-tag with `4.0.0-canary.1`), try again.

**Comment by tunnckoCore** [comment]
Okay. The `4.0.0-canary.20` is working now :) Just update.

**Comment by zeke** [comment]
Thanks @tunnckoCore. I installed `next` and pushed it up. Let's see how it goes!

**Comment by tunnckoCore** [comment]
new canary was published, canary-20200124.1

tests of this pkg are passing. and with it we can address #43. all methos and utils are exposed, check the readme in the tunnckoCore/opensource monorepo. all methods also accepts options param - headerRegex, caseSensitive and normalize.

so you can try passing headerRegex to resolve #43

**Comment by cdaringe** [comment]
@tunnckoCore @zeke , canary of parse-commit-message `src/index.js` ===

```
'use strict';

// eslint-disable-next-line import/no-unresolved
const mod = require('./dist/cjs');

function interop(x) {
  if (Object.keys(x).length === 1 && x.default) {
    return x.default;
  }
  return x;
}

module.exports = interop(mod);
```

where the tree for the module is:

```
$ tree /path/to/stuff/node_modules/parse-commit-message/
├── CHANGELOG.md
├── index.js
└── package.json
```

can we revisit the publish step?

**Comment by tunnckoCore** [comment]
Lock the version strictly to that canary... for now.

**Comment by cdaringe** [comment]
@tunnckoCore thx.

`4.0.0-canary.20200124.9` resolved, but `4.0.0-canary-20200124.1` did not 👍 :fyi:

**Pull request merged**
