### PR TITLE
Revert "build(deps): upgrade conventional-commit-types to v3.0.0"

### PR DESCRIPTION
**Pull request by zeke**
Reverts zeke/semantic-pull-requests#94

Not sure what this PR broke, but I'm pretty sure it broke something.

cc @codebytere 

cc @felipecassiors

### CODE REVIEW

**Comment by felipecassiors** [comment]
I see `.travis.yml` at the root of the repo, but I can't see any log. Is it private?

**Comment by zeke** [comment]
I didn't notice the tests had stopped running. That must have been when I migrated this repo from the @probot org to my @zeke account.

I just landed https://github.com/zeke/semantic-pull-requests/pull/97 to migration from Travis to Actions. If you'd like to open a followup PR and try again, that would be helpful. I would suggest maybe just updating the one `conventional-commit-types` dependency to avoid breaking things unexpectedly. If you could also look into the breaking change between v2 and v3 of that package, that would be helpful.

Thanks!

**Comment by felipecassiors** [comment]
@zeke https://github.com/commitizen/conventional-commit-types/compare/v2.3.0...v3.0.0

**Comment by zeke** [comment]
Huh. So it was probably some other dep update in #94 that broke the build.

**Pull request merged**
