### PR TITLE
chore: Bump node version number from 8 to 14.

### PR DESCRIPTION
**Pull request by tysonkamp**

### CODE REVIEW

**Comment by zeke** [comment]
Thanks for the PR. Can you explain why you chose v14? Looks like that version is in maintenance mode and we should be running on 16 or 18: https://nodejs.org/en/about/releases/

**Comment by tysonkamp** [comment]
The requestor suggested minimum 12 or 14 (it was a staleness issues).  I have no objection to 17 which I believe is current.

**Comment by tysonkamp** [comment]
Will open a new PR.

**Comment by zeke** [comment]
No problem, but for future reference you shouldn't have to close and open a new PR. You can push additional commits to the same branch with your changes.

**Pull request closed without merging**
